// ignore_for_file: non_constant_identifier_names
part of 'resources.dart';

const _stringResources = (
  app_name: 'app_name',
  landing: (
    welcome: 'landing.welcome',
    description: 'landing.description',
  ),
  device_connection: (
    manage_devices: 'device_connection.manage_devices',
    add_manually: 'device_connection.add_manually',
    id: 'device_connection.id',
    ip_address: 'device_connection.ip_address',
    cancel: 'device_connection.cancel',
    request_pair: 'device_connection.request_pair',
    connect: 'device_connection.connect',
    connected_devices: 'device_connection.connected_devices',
    disconnected_devices: 'device_connection.disconnected_devices',
    add_device: 'device_connection.add_device',
    no_devices_found: 'device_connection.no_devices_found',
    no_connected_devices: 'device_connection.no_connected_devices',
    available_devices: 'device_connection.available_devices',
    requested_devices: 'device_connection.requested_devices',
    paired_devices: 'device_connection.paired_devices',
    rescan: 'device_connection.rescan',
    warning: 'device_connection.warning',
    delete_device_confirmation: 'device_connection.delete_device_confirmation',
    unpair: 'device_connection.unpair',
    pair_hint: 'device_connection.pair_hint',
  ),
  home: (
    manage_devices: 'home.manage_devices',
    information: 'home.information',
    file_explorer: 'home.file_explorer',
    gallery: 'home.gallery',
    messages: 'home.messages',
    notifications: 'home.notifications',
    rename_this_device: 'home.rename_this_device',
    save: 'home.save',
    cancel: 'home.cancel',
  ),
  status: (
    connected: 'status.connected',
    disconnected: 'status.disconnected',
    connected_at: 'status.connected_at',
    device_offline: 'status.device_offline',
  ),
  messages: (
    conversations: 'messages.conversations',
    conversation_not_chosen: 'messages.conversation_not_chosen',
    hint: 'messages.hint',
    me: 'messages.me',
  ),
);
