// ignore_for_file: non_constant_identifier_names
part of 'resources.dart';

const _vectorResources = (
  error: 'assets/vectors/error.svg',
  warning: 'assets/vectors/warning.svg',
  gallery: 'assets/vectors/gallery.svg',
  notification: 'assets/vectors/notification.svg',
  exchange: 'assets/vectors/exchange.svg',
  linux: 'assets/vectors/linux.svg',
  battery_bolt: 'assets/vectors/battery_bolt.svg',
  volume_mute: 'assets/vectors/volume_mute.svg',
  settings: 'assets/vectors/settings.svg',
  add: 'assets/vectors/add.svg',
  battery_quarter: 'assets/vectors/battery_quarter.svg',
  smartphone: 'assets/vectors/smartphone.svg',
  link: 'assets/vectors/link.svg',
  phone_android: 'assets/vectors/phone_android.svg',
  battery_empty: 'assets/vectors/battery_empty.svg',
  app_icon_monochrome: 'assets/vectors/app_icon_monochrome.svg',
  battery_three_quarters: 'assets/vectors/battery_three_quarters.svg',
  pending: 'assets/vectors/pending.svg',
  volume_down: 'assets/vectors/volume_down.svg',
  android: 'assets/vectors/android.svg',
  messages: 'assets/vectors/messages.svg',
  phone_ring: 'assets/vectors/phone_ring.svg',
  battery_full: 'assets/vectors/battery_full.svg',
  menu: 'assets/vectors/menu.svg',
  edit: 'assets/vectors/edit.svg',
  unlink: 'assets/vectors/unlink.svg',
  battery_half: 'assets/vectors/battery_half.svg',
  battery_exclamation: 'assets/vectors/battery_exclamation.svg',
  app_icon: 'assets/vectors/app_icon.svg',
  windows: 'assets/vectors/windows.svg',
  info: 'assets/vectors/info.svg',
  computer: 'assets/vectors/computer.svg',
  volume_off: 'assets/vectors/volume_off.svg',
  no_sound: 'assets/vectors/no_sound.svg',
);
